# .github/workflows/snyk-scan.yml
name: Snyk example

on:
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master

      # Step 3: Set up Go (if required for your project)
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.19'

      # Step 4: Run Snyk test
      - name: Snyk test
        run: snyk test
        env:
          SNYK_TOKEN: d79e3f70-b203-4093-b6ed-a6236409e45b
